### ISSUE TITLE
`0.14.0.post1` sdist has broken `pyproject.toml`

### ISSUE THREAD

**Issue by mgorny** [trezor/cython-hidapi#180]
Not sure what went wrong here but [0.14.0.post1 sdist](https://files.pythonhosted.org/packages/3b/8e/8c0e2c81f155413e4127adc4ced9e10059a0c67c9aaf35d32e3cbf44f0f4/hidapi-0.14.0.post1.tar.gz) contains a `pyproject.toml` that doesn't match the git tag, and has multiple problems:

```
[tool.poetry]
name = "hidapi"
version = "0.1.0"
description = ""
authors = ["Pavol Rusnak <pavol@rusnak.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
cython = "^3.0.10"
twine = "^5.1.1"
setuptools = "^71.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Since it specifies `poetry-core` as the build backend, all PEP517 builders will use it rather than `setup.py`. Since the file doesn't work at all, this means it is impossible to install it at all. To reproduce:

```pytb
$ pip install --no-binary hidapi hidapi
Collecting hidapi
  Downloading hidapi-0.14.0.post1.tar.gz (172 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.6/172.6 kB 2.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "/tmp/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/tmp/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-mb5uwtav/overlay/lib/python3.12/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
          builder = WheelBuilder(poetry)
                    ^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-mb5uwtav/overlay/lib/python3.12/site-packages/poetry/core/masonry/builders/wheel.py", line 62, in __init__
          super().__init__(poetry, executable=executable)
        File "/tmp/pip-build-env-mb5uwtav/overlay/lib/python3.12/site-packages/poetry/core/masonry/builders/builder.py", line 55, in __init__
          self._meta = Metadata.from_package(self._package)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-mb5uwtav/overlay/lib/python3.12/site-packages/poetry/core/masonry/metadata.py", line 58, in from_package
          with readme.open(encoding="utf-8") as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/pathlib.py", line 1013, in open
          return io.open(self, mode, buffering, encoding, errors, newline)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-eca923yc/hidapi_796bd5457d12435eb258bfe7f3b33f5c/README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Even if readme path weren't invalid, `hidapi` is not a pure Python package, so poetry-core will never be able to correctly install it. Besides, the version and description are wrong, and dependencies are incorrect.

**Comment by prusnak** [comment]
hopefully this is fixed with https://pypi.org/project/hidapi/0.14.0.post2/

please reopen if it is not

**Comment by mgorny** [comment]
Thanks, that one seems to have the correct `pyproject.toml`.

As a side note, this is not a big deal but this doesn't seem to be a correct way to use post releases:

> Some projects use post-releases to address minor errors in a final release that do not affect the distributed software (for example, correcting an error in the release notes).
> […]
> Note: The use of post-releases to publish maintenance releases containing actual bug fixes is strongly discouraged. In general, it is better to use a longer release number and increment the final component for each maintenance release.

https://packaging.python.org/en/latest/specifications/version-specifiers/#post-releases

**Comment by prusnak** [comment]
@mgorny this is different because i want to keep the version the same as the bundled hidapi version. if i bumped my package to 0.14.1 one might think that the bundled hidapi is 0.14.1 while it is 0.14.0 creating confusion

**Comment by mgorny** [comment]
You could do 0.14.0.1. That's what `apsw` does.
