### ISSUE TITLE
Failure to build on arm64

### ISSUE THREAD

**Issue by clehner** [trezor/cython-hidapi#72]
Python 3.6.9
`Linux pinebook 4.19.63-sunxi64 #5.92 SMP Fri Aug 2 00:18:27 CEST 2019 aarch64 aarch64 aarch64 GNU/Linux`
This is after running `pip3 install --upgrade --user setuptools` and `pip3 install --upgrade --user wheel`.
Build & installation works if I use python2... but I need python3 for this.

```
cython-hidapi$ python3 setup.py install --user
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "/home/cel/.local/lib/python3.6/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp_0v6lho6', '--quiet', 'Cython']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 128, in <module>
    install_requires = ['setuptools>=19.0'],
  File "/home/cel/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/home/cel/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/home/cel/.local/lib/python3.6/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/cel/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/home/cel/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/cel/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/cel/.local/lib/python3.6/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/home/cel/.local/lib/python3.6/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp_0v6lho6', '--quiet', 'Cython']' returned non-zero exit status 1.
```

**Comment by benoit-pierre** [comment]
Is that the full traceback? What if you install Cython beforehand?

**Comment by benoit-pierre** [comment]
You should be able to get more traces from the pip sub-process invocation by setting `PIP_VERBOSE=1` in your environment before running the command.

**Comment by clehner** [comment]
Thanks @benoit-pierre. I was missing Cython. (I had just the cython package for Python 2). After installing deb packages cython3 and python3-dev, build and installation completed.

Ubuntu 18.04.3 LTS
